"""upgrade table rest

Revision ID: 0ee84b1d22ad
Revises: 4451886d5acd
Create Date: 2025-06-30 17:34:08.645881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee84b1d22ad'
down_revision: Union[str, None] = '4451886d5acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Restaurants', 'comments',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Restaurants', 'comments',
               existing_type=sa.String(length=2500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
