"""add tables

Revision ID: 653c34d4b8f2
Revises: 0ecafb6d6f1f
Create Date: 2025-06-21 10:02:10.651099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '653c34d4b8f2'
down_revision: Union[str, None] = '0ecafb6d6f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('main_image', sa.String(), nullable=False))
    op.add_column('Restaurants', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=False))
    op.alter_column('Restaurants', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('Restaurants', 'menu',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Restaurants', 'feedback',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_column('Restaurants', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('Restaurants', 'feedback',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Restaurants', 'menu',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Restaurants', 'description',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('Restaurants', 'images')
    op.drop_column('Restaurants', 'main_image')
    # ### end Alembic commands ###
