"""add comment to user

Revision ID: 5300a4d52af7
Revises: e638c5f25ca6
Create Date: 2025-06-30 15:50:43.353712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5300a4d52af7'
down_revision: Union[str, None] = 'e638c5f25ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('users', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comments', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.drop_column('users', 'comment')
    # ### end Alembic commands ###
