"""upgrade table rest add comments

Revision ID: 4451886d5acd
Revises: ca48a73d2b37
Create Date: 2025-06-30 17:13:58.536496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4451886d5acd'
down_revision: Union[str, None] = 'ca48a73d2b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('comments', sa.Text(), nullable=True))
    op.drop_column('Restaurants', 'feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('Restaurants', 'comments')
    # ### end Alembic commands ###
